### ISSUE TITLE
There's a way to make all contents of window an PDF ?

### ISSUE THREAD

**Issue by DouglasHennrich** [benbahrenburg/benCoding.PDF#6]
I want to generate an PDF of ALL my contents on my window... the thing is... my window has an scrollView that have some information outside the screen... there's a way to get this informations outside to generate the PDF too?

I tried to use win.toImage() but it's like Ti.Media.takeScreenshot ... only show what's on screen.

Thanks for your module!

**Comment by benbahrenburg** [comment]
Unfortunately this scenario wouldn't be covered by this module.  You might try rendering the full screen for a second to get a complete view ( think like a print page on the web ). Another option would be to render sections and stick them together into on full view.
