### ISSUE TITLE
How I add new page?

### ISSUE THREAD

**Issue by Mritunjaysingh** [benbahrenburg/benCoding.PDF#7]
Hello,
I have need convert multiple PDF Pages. If My data is not arrange in one page. then How I will do this. Please suggest me any idea. 

Thanks

**Comment by benbahrenburg** [comment]
Hi @Mritunjaysingh the module doesn't support this. You would need to add this functionality yourself.  I accept PRs if you want to add it to the module, although this would seem to be easier to tackle in JS.
